### ISSUE TITLE
NVMe device registration fail

### ISSUE THREAD

**Issue by sooyun802** [DFC-OpenSource/ox-ctrl#14]
Hello, 

I am trying to run ox-ctrl-volt with the DFC board.

I've followed the instructions on setting the host with pblk. However, it does not seem to be working.

![image](https://user-images.githubusercontent.com/26572842/47922608-cc904f80-defa-11e8-8716-a5c79e1fa68e.png)

Linux 4.13 was used for the host.

Are there any steps that I've forgotten to follow?

Thanks.

**Comment by dsavic11** [comment]
Hello sooyun802 ,
Could you please provide a detailed system configuration (server config, Linux version, DFC config, etc)?
Thanks,
Dragan
dsavic11@gmail.com

**Comment by dsavic11** [comment]
Hello sooyun802 ,
Could you please provide a detailed system configuration (server config,
DFC config - SW and HW - like with or without NAND DIMMs,, etc)?
Thanks,
Dragan
dsavic11@gmail.com

**Comment by sooyun802** [comment]
Hello,

It turned out that the problem was the order between turning on the host computer and starting the ox-ctrl program.

Thanks,
Sooyun
