### ISSUE TITLE
Too much memory allocated for queues (minor)

### ISSUE THREAD

**Issue by freysteinn** [DFC-OpenSource/ox-ctrl#6]
The code in nvme.c which allocates memory for the completion and submission queues allocate too much memory. The definition of the completion and submission queues are double pointers as follows:
    NvmeSQ          **sq;
    NvmeCQ          **cq;

But the function static int nvme_init_ctrl (NvmeCtrl *n) allocates memory as if they are a single pointer, and on top of that it uses the size of NvmeCQ for sq and NvmeSQ for cq.
    n->sq = calloc (1, sizeof (NvmeCQ)*((n->features.num_queues & 0xfffe) + 1));
    n->cq = calloc (1, sizeof (NvmeSQ)*((n->features.num_queues >> 16) + 1));

This does not make the code nonfunctional, but it makes it harder to read and it wastes space.
The rest of the code does assume double pointers.

**Comment by ivpi** [comment]
Fixed
